name: build-and-test
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  npm-install:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - id: cache
        name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Npm Install
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
  build:
    runs-on: ubuntu-20.04
    needs: [npm-install]
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Build
        run: npm run build:ci

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
  test:
    runs-on: ubuntu-20.04
    needs: [npm-install]
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Restore node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Test
        run: npm run build:ci
